version: "3.8"

services:
  backend:
    build:
      context: https://github.com/basbloemendaal/poker-solver-backend.git
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: https://github.com/basbloemendaal/poker-solver-frontend.git
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
